#!/usr/local/bin/ruby
#
#   svn-tags - 
#   	$Release Version: $
#   	$Revision: 1.1 $
#   	$Date: 1997/08/08 00:57:08 $
#   	by Keiju ISHITSUKA
#
# --
#
#   
#

@RCS_ID='-$Id:  $-'

system("svn copy . http://localhost/svn/repos/tags/#{ARGV[0]}")

