#!/usr/local/bin/ruby
#
#   svn-tags - 
#   	$Release Version: $
#   	$Revision: 1.1 $
#   	$Date: 1997/08/08 00:57:08 $
#   	by Keiju ISHITSUKA
#
# --
#
#   
#

@RCS_ID='-$Id:  $-'

tag = ARGV[0]
unless /^v([0-9.]+-[0-9]+)-.*$/ =~ tag
  raise "バージョン形式が間違っています(#{tag})"
end

ver = $1

File.open("version.rb", "w") do |io|
  io << "#\n"
  io << "# Don't modified this file.\n"
  io << "# This file is auto generation. \n"
  io << "#\n"
  io << "module Fairy\n"
  io << "    Version = \"#{ver}\"\n"
  io << "end\n"
  io << "\n"
end

system("svn ci -m 'version: #{ver}' version.rb")

system("svn copy . http://localhost/svn/repos/fairy/tags/#{ARGV[0]}")

