#!/usr/bin/env ruby
# encoding: UTF-8
#
# Copyright (C) 2007-2010 Rakuten, Inc.
#

require "optparse"
require "deep-connect/deep-connect"

require "fairy/share/base-app"
require "fairy/share/conf"
require "fairy/share/locale"
require "fairy/share/encoding"
require "fairy/main/controller"

$0 = "fairy controller #{ARGV.join(' ')}"

module Fairy
  class ControllerAPP<BaseAPP
    def initialize
      super
      
      @master_port = Fairy::CONF.MASTER_PORT
      @id = nil
    end

    def option_parser
      super do |opt|
	opt.on("--master=VAL"){|val| @master_port = val}
	opt.on("--id=VAL"){|val| @id = val.to_i}
      end
    end

    def start
      Fairy::Controller.start(@id, @master_port)
    end
  end
end

Fairy::ControllerAPP.start
sleep
