#!/usr/bin/env ruby
# encoding: UTF-8
#
# Copyright (C) 2007-2010 Rakuten, Inc.
#

require "optparse"

require "deep-connect/deep-connect"

require "fairy/share/base-app"
require "fairy/share/conf"
require "fairy/share/locale"
require "fairy/share/encoding"
require "fairy/main/master"

$0 = "fairy master #{ARGV.join(' ')}"

module Fairy
  class MasterAPP<BaseAPP
    def initialize
      super
      @master_port = Fairy::CONF.MASTER_PORT
    end

#    def parse_arg
#      super
#    end

    def option_parser
      super do |opt|
	opt.on("-p", "--master_port=VAL"){|val| @master_port = val}
      end
    end
    
    def start
      Fairy::Master.start(@master_port)
    end
  end
end

Fairy::MasterAPP.start
sleep
